name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: 
      - v*
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set environments
      run: echo "::set-env name=TAG::$(git tag --points-at HEAD | cut -c 2-4)"
    
    - name: build
      run: docker-compose build helloworld
    
    - name: push image
      if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
      run: echo "TODO publish docker image"
