name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: 
      - v*
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set environments
      run: echo Tag for the image $TAG
      env:
        TAG: $(git tag --points-at HEAD)
    
    - name: build
      run: docker-compose build helloworld
    
    - name: push image
      if: github.ref == 'refs/heads/master'
      run: echo "TODO publish docker image"
